[package]
name = "connect4-wasm"
version = "0.1.0"
authors = ["Karl van Workum <karl.vanworkum@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.5.1"
wasm-bindgen = "^0.2.50"
