[package]
name = "connect4-wasm"
version = "0.2.0"
authors = ["Karl van Workum <karl.vanworkum@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
serde = "1.0"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
gloo = "0.10"
